-- Local `supabase db reset` seed hook.
--
-- Study content (kanji / vocab / grammar) and badges are treated as versioned
-- reference data and live in MIGRATIONS (20260712000005_content_n5_n4.sql) so
-- they deploy to every environment via `supabase db push`. Nothing extra is
-- seeded here yet; add dev-only throwaway data below if needed.
