import "server-only";
import { createClient } from "@/lib/supabase/server";
import { createServiceClient } from "@/lib/supabase/service";
import { requireUser } from "@/lib/data/videos";
import { getActivePlanTier } from "@/lib/data/subscriptions";
import { rateLimit } from "@/lib/rate-limit";
import { fingerprint } from "@/lib/knowledge/canonical";
import { readKnowledgeConfig } from "@/lib/knowledge/config";
import { getOrGenerateSection, type GenerateDeps, type GenerateOutcome } from "@/lib/knowledge/orchestrator";
import { nextUtcMidnight, nextUtcMonth, utcDay, utcMonth } from "@/lib/knowledge/periods";
import { contextKeyFor, sectionDefinition } from "@/lib/knowledge/registry";
import type { KnowledgeSection } from "@/lib/knowledge/types";
import type { KnowledgeSectionRequest } from "@/lib/validation/knowledge";

const SECTION_LIMIT = { limit: 30, windowMs: 60_000 };
const USAGE_LIMIT = { limit: 60, windowMs: 60_000 };

type Refusal =
  | { kind: "unauthorized" }
  | { kind: "rate_limited"; retryAfter: number }
  | { kind: "invalid" }
  | { kind: "not_found" };

export type KnowledgeSectionResult = Refusal | { kind: "outcome"; section: KnowledgeSection; outcome: GenerateOutcome };

export interface LearnerLine {
  id: string;
  textJp: string;
  videoId: string;
  videoTitle: string;
}

/** The line under the learner's own RLS: a line they cannot read is null, exactly like one that does not exist. */
export async function getLineForLearner(supabase: ReturnType<typeof createClient>, lineId: string): Promise<LearnerLine | null> {
  const { data, error } = await supabase
    .from("transcript_lines")
    .select("id, text_jp, transcripts!inner(video_id, videos!inner(title))")
    .eq("id", lineId)
    .maybeSingle();
  if (error) throw error;
  const row = data as { id: string; text_jp: string | null; transcripts: { video_id: string; videos: { title: string } } } | null;
  if (!row?.text_jp) return null;
  return { id: row.id, textJp: row.text_jp, videoId: row.transcripts.video_id, videoTitle: row.transcripts.videos.title };
}

/** A span must lie inside the text and must not cut a surrogate pair (𠮷 is two UTF-16 units). Task 9 snaps to tokens. */
function spanIsValid(text: string, span: { start: number; end: number }): boolean {
  if (span.end > text.length) return false;
  const splits = (index: number) => index > 0 && index < text.length && /[\uDC00-\uDFFF]/.test(text.charAt(index));
  return !splits(span.start) && !splits(span.end);
}

/** POST /api/knowledge/sections (spec §5.3 flow, steps 1–2; the orchestrator does the rest). */
export async function requestKnowledgeSection(body: KnowledgeSectionRequest, deps: GenerateDeps = {}): Promise<KnowledgeSectionResult> {
  const supabase = createClient();
  const user = await requireUser(supabase);
  if (!user) return { kind: "unauthorized" };
  const limit = rateLimit(`knowledge:section:${user.id}`, SECTION_LIMIT);
  if (!limit.ok) return { kind: "rate_limited", retryAfter: limit.retryAfter };

  const definition = sectionDefinition(body.section);
  // System-funded sections are generated by their own routes, never on a learner's request.
  if (!definition || definition.access === "system") return { kind: "invalid" };
  const takesSpan = definition.contextPolicy === "parent_sentence";
  if (takesSpan !== (body.span !== undefined)) return { kind: "invalid" };

  const line = await getLineForLearner(supabase, body.transcriptLineId);
  if (!line) return { kind: "not_found" };
  if (body.span && !spanIsValid(line.textJp, body.span)) return { kind: "invalid" };

  const parentFingerprint = fingerprint(line.textJp);
  const phrase = body.span ? line.textJp.slice(body.span.start, body.span.end) : undefined;
  const outcome = await getOrGenerateSection({
    definition,
    locale: body.locale,
    targetText: phrase ?? line.textJp,
    contextKey: contextKeyFor(definition, { videoId: line.videoId, parentFingerprint }),
    parentFingerprint,
    tier: await getActivePlanTier(user.id),
    billing: { scope: "learner", userId: user.id },
    // Context-free sections ignore what they are not keyed by (registry.test.ts proves it).
    promptInput: { sentence: line.textJp, phrase, locale: body.locale, videoTitle: line.videoTitle },
  }, deps);
  return { kind: "outcome", section: definition.section, outcome };
}

export type KnowledgeUsage =
  | { plan: "free"; used: number; limit: number; resetsAt: string }
  | { plan: "plus"; remainingPercent: number; resetsAt: string };

/** GET /api/knowledge/usage: counts and reset times only — never tokens, USD or raw credits for Plus. */
export async function getKnowledgeUsage(now = new Date()): Promise<Exclude<Refusal, { kind: "invalid" | "not_found" }> | { kind: "ok"; usage: KnowledgeUsage }> {
  const supabase = createClient();
  const user = await requireUser(supabase);
  if (!user) return { kind: "unauthorized" };
  const limit = rateLimit(`knowledge:usage:${user.id}`, USAGE_LIMIT);
  if (!limit.ok) return { kind: "rate_limited", retryAfter: limit.retryAfter };

  const [tier, snapshot] = await Promise.all([
    getActivePlanTier(user.id),
    createServiceClient().rpc("ai_usage_snapshot", { p_user: user.id, p_day: utcDay(now), p_month: utcMonth(now) }),
  ]);
  if (snapshot.error) throw snapshot.error;
  const used = snapshot.data as { freeSentencesUsed: number; plusCreditsUsed: number };
  const config = readKnowledgeConfig();
  if (tier === "free") {
    return { kind: "ok", usage: { plan: "free", used: used.freeSentencesUsed, limit: config.freeSentencesPerDay, resetsAt: nextUtcMidnight(now).toISOString() } };
  }
  const remaining = 1 - used.plusCreditsUsed / config.plusCreditsPerMonth;
  return {
    kind: "ok",
    usage: { plan: "plus", remainingPercent: Math.max(0, Math.floor(remaining * 100)), resetsAt: nextUtcMonth(now).toISOString() },
  };
}
