import type { ComponentProps } from "react";
import Image from "next/image";
import { Link } from "@/lib/i18n/navigation";

export interface HubLessonCardLesson {
  id: string;
  youtubeVideoId: string;
  title: string;
  durationSeconds: number | null;
  thumbnailUrl: string | null;
  jlptLevelEstimate: string | null;
}

export interface HubLessonProgress {
  /** A measured progress percentage in the inclusive range 0â€“100. */
  percent: number;
  /** Localized, human-readable description of the recorded progress. */
  label: string;
}

export interface HubLessonCardProps {
  lesson: HubLessonCardLesson;
  href: ComponentProps<typeof Link>["href"];
  actionLabel: string;
  noThumbnailLabel: string;
  progress?: HubLessonProgress;
  /** A localized, evidence-backed learning detail, never generated by the card. */
  detail?: string;
}

/**
 * A data-only lesson card shared by Hub shelves and the later Explore screen.
 * It owns no fetches and accepts display copy from its localized parent.
 */
export function HubLessonCard({ lesson, href, actionLabel, noThumbnailLabel, progress, detail }: HubLessonCardProps) {
  const progressPercent = progress ? Math.max(0, Math.min(100, progress.percent)) : null;

  return (
    <li>
      <Link
        href={href}
        aria-label={`${actionLabel}: ${lesson.title}`}
        className="group flex h-full flex-col overflow-hidden rounded-xl border border-border bg-card shadow-raised transition-colors hover:border-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 focus-visible:ring-offset-background"
      >
        <div className="relative aspect-video w-full shrink-0 overflow-hidden bg-muted">
          {lesson.thumbnailUrl ? (
            <Image
              src={lesson.thumbnailUrl}
              alt=""
              fill
              sizes="(min-width: 1280px) 22rem, (min-width: 640px) 50vw, 100vw"
              className="object-cover transition-transform duration-base group-hover:scale-[1.02] motion-reduce:transform-none"
            />
          ) : (
            <div className="flex h-full items-center justify-center text-sm text-muted-foreground">{noThumbnailLabel}</div>
          )}
          {lesson.jlptLevelEstimate && (
            <span className="absolute left-sm top-sm rounded-full bg-background/90 px-sm py-2xs text-caption font-semibold text-foreground">
              {lesson.jlptLevelEstimate}
            </span>
          )}
        </div>

        <div className="flex flex-1 flex-col gap-sm p-md-lg">
          <h3 className="line-clamp-2 text-body font-semibold text-foreground">{lesson.title}</h3>
          {detail ? <p className="text-sm text-muted-foreground">{detail}</p> : null}
          {progress && progressPercent !== null && (
            <div className="mt-auto space-y-xs">
              <p className="text-caption text-muted-foreground">{progress.label}</p>
              <div
                role="progressbar"
                aria-label={progress.label}
                aria-valuemin={0}
                aria-valuemax={100}
                aria-valuenow={progressPercent}
                className="h-1.5 overflow-hidden rounded-full bg-muted"
              >
                <div className="h-full rounded-full bg-primary" style={{ width: `${progressPercent}%` }} />
              </div>
            </div>
          )}
          <span className="mt-auto text-sm font-semibold text-primary-strong group-hover:underline group-hover:underline-offset-4">
            {actionLabel}
          </span>
        </div>
      </Link>
    </li>
  );
}
