/**
 * Frozen copy of `NAV_GROUPS` as it shipped BEFORE the Phase 1a registry
 * refactor, captured first so T6 (spec R8) compares the derivation against a
 * real baseline rather than against its own output.
 *
 * ⛔ DO NOT EDIT THIS FILE IN PHASE 1a. It is the definition of "zero visual
 * diff". Phase 1b re-freezes it against the LOCKED IA
 * (docs/product/ia-proposal.md §2) as a deliberate, separate commit.
 *
 * `journey` pointing at `/journal` is a known defect the LOCKED IA fixes in
 * Phase 1b (decision-register.md A8). It is preserved here on purpose: 1a
 * proves the engine, 1b changes the product decision.
 */
export const NAV_BASELINE = [
  {
    key: "learn",
    items: [
      { href: "/dashboard", key: "dashboard" },
      { href: "/shadowing", key: "lessons" },
      { href: "/kanji", key: "kanji" },
      { href: "/vocab", key: "vocab" },
      { href: "/grammar", key: "grammar" },
      { href: "/reading", key: "reading" },
      { href: "/conversation", key: "speaking" },
      { href: "/jlpt", key: "jlpt" },
    ],
  },
  {
    key: "study",
    items: [
      { href: "/review", key: "review" },
      { href: "/mining", key: "mining" },
      { href: "/playlists", key: "playlists" },
      { href: "/challenges", key: "challenges" },
      { href: "/community", key: "community" },
      { href: "/leaderboard", key: "leaderboard" },
    ],
  },
  {
    key: "insights",
    items: [
      { href: "/sensei", key: "sensei" },
      { href: "/roadmap", key: "roadmap" },
      { href: "/weekly-report", key: "weeklyReport" },
    ],
  },
  {
    key: "progress",
    items: [
      { href: "/journal", key: "journey" },
      { href: "/statistics", key: "statistics" },
      { href: "/achievements", key: "achievements" },
    ],
  },
  {
    key: "account",
    items: [
      { href: "/profile", key: "profile" },
      { href: "/settings", key: "settings" },
    ],
  },
] as const;
