import type { ScreenEntry } from "./screen-registry-types";

/**
 * The screen registry — one row per product screen, joined to the frame that
 * designed it (Figma) and the route that ships it (repo), as of the Phase 0
 * inventory (`docs/product/screen-inventory.md`, all 57 frames read
 * 2026-08-12) and today's `components/layout/app-nav.tsx`.
 *
 * ⛔ Phase 1a records navigation and identity EXACTLY as they ship today.
 * The approved IA in `docs/product/ia-proposal.md` (renaming `/jlpt`, hiding
 * `/vocab`, adding `/companion`, moving `journey` to `/roadmap`, etc.) is
 * NOT applied here — including rows that look wrong (`journey` → `/journal`,
 * `/vocab` still in nav despite the 2026-08-11 "hide" ruling). A later phase
 * changes them deliberately.
 *
 * Sourcing, per the brief's authority order:
 *   1. `docs/product/figma-frame-map.md` — figmaNodeId + `name` (verbatim
 *      frame name, trimmed — never the on-screen headline or the inventory's
 *      discovered "true identity").
 *   2. `docs/product/screen-inventory.md` Part II §6–§20 — `kind`, and for
 *      state-variants, `variantOf`.
 *   3. `listPageRoutes(process.cwd())` — `route` + `chrome`, the authoritative
 *      44-route set (verified twice independently: `npx tsx` + the recursive
 *      walk one-liner both return 44).
 *   4. `components/layout/app-nav.tsx` + `lib/product/nav-baseline.fixture.ts`
 *      — `navGroup` + `navOrder` for the 22 fixed nav-key screenIds.
 *
 * `impl` is measured, not asserted: `grep -rln "UpcomingScreen" app/` names
 * exactly 9 files (achievements, challenges, review, roadmap, sensei,
 * settings, shadowing/explore, statistics, weekly-report) — those 9 routes
 * are `impl: "placeholder"`; every other existing route is `impl: "built"`.
 */
export const SCREEN_REGISTRY: readonly ScreenEntry[] = [
  // ===================================================================
  // Nav destinations (22) — kind/impl/figma vary per row; navGroup/navOrder
  // are fixed by today's app-nav.tsx §learn/study/insights/progress/account.
  // ===================================================================

  // learn/1 — designed, built. Frame name is "Homepage"; the SCREEN is the
  // Dashboard (§19.1 — the picture, not the layer name, is the evidence).
  {
    screenId: "dashboard",
    name: "Homepage",
    kind: "screen",
    variantOf: null,
    figmaNodeId: "111:515",
    repoOnlyReason: null,
    figmaCheckedAt: "2026-08-12",
    route: "/dashboard",
    chrome: "app",
    impl: "built",
    navGroup: "learn",
    navOrder: 1,
  },
  // learn/2 — designed, built. Frame not renamed despite the rename pass
  // targeting it (figma-frame-map.md); name recorded as it stands today.
  {
    screenId: "lessons",
    name: "Shadowing hub after changes",
    kind: "screen",
    variantOf: null,
    figmaNodeId: "149:2",
    repoOnlyReason: null,
    figmaCheckedAt: "2026-08-12",
    route: "/shadowing",
    chrome: "app",
    impl: "built",
    navGroup: "learn",
    navOrder: 2,
  },
  // learn/3 — JUDGEMENT CALL: /kanji matches NEITHER designed kanji screen
  // (screen-inventory.md §6.0 — "the shipped screen is a thin catalogue that
  // neither design describes"). Recorded repo-only rather than borrowing
  // either frame's id. The two real kanji screens get their own entries
  // below (kanji-explorer, kanji-library), unattached to any route.
  {
    screenId: "kanji",
    name: "Kanji",
    kind: "repo-only",
    variantOf: null,
    figmaNodeId: null,
    repoOnlyReason: "legacy-unreviewed",
    figmaCheckedAt: null,
    route: "/kanji",
    chrome: "app",
    impl: "built",
    navGroup: "learn",
    navOrder: 3,
  },
  // learn/4 — no frame in the 57 covers Vocab (§4); built today regardless
  // of the 2026-08-11 "hide, reversibly" ruling, which Phase 1a does not apply.
  {
    screenId: "vocab",
    name: "Vocabulary",
    kind: "repo-only",
    variantOf: null,
    figmaNodeId: null,
    repoOnlyReason: "legacy-unreviewed",
    figmaCheckedAt: null,
    route: "/vocab",
    chrome: "app",
    impl: "built",
    navGroup: "learn",
    navOrder: 4,
  },
  // learn/5 — JUDGEMENT CALL: `Grammar analysis` (284:1464) is a sentence
  // parser, explicitly NOT the /grammar catalogue (§17.1: "the two are not
  // comparable"). So /grammar itself has no frame; 284:1464 gets its own
  // entry below (grammar-analysis), route null.
  {
    screenId: "grammar",
    name: "Grammar",
    kind: "repo-only",
    variantOf: null,
    figmaNodeId: null,
    repoOnlyReason: "legacy-unreviewed",
    figmaCheckedAt: null,
    route: "/grammar",
    chrome: "app",
    impl: "built",
    navGroup: "learn",
    navOrder: 5,
  },
  // learn/6 — no frame anywhere in the 57 covers Reading.
  {
    screenId: "reading",
    name: "Reading",
    kind: "repo-only",
    variantOf: null,
    figmaNodeId: null,
    repoOnlyReason: "legacy-unreviewed",
    figmaCheckedAt: null,
    route: "/reading",
    chrome: "app",
    impl: "built",
    navGroup: "learn",
    navOrder: 6,
  },
  // learn/7 — designed (≈), built. `/conversation` renders the library shell
  // (170:9364); the live-session frame (44:7289) has no route of its own
  // (§15.6 — "session UI exists in-page") and gets a separate entry below.
  {
    screenId: "speaking",
    name: "Conversation practice library",
    kind: "screen",
    variantOf: null,
    figmaNodeId: "170:9364",
    repoOnlyReason: null,
    figmaCheckedAt: "2026-08-12",
    route: "/conversation",
    chrome: "app",
    impl: "built",
    navGroup: "learn",
    navOrder: 7,
  },
  // learn/8 — designed (≈), built. Frame's layer name is "JLPT Practice";
  // its on-screen identity is "Certification Practice" (§10.0) — name field
  // stays the layer name, per the Dashboard precedent above.
  {
    screenId: "jlpt",
    name: "JLPT Practice",
    kind: "screen",
    variantOf: null,
    figmaNodeId: "232:2",
    repoOnlyReason: null,
    figmaCheckedAt: "2026-08-12",
    route: "/jlpt",
    chrome: "app",
    impl: "built",
    navGroup: "learn",
    navOrder: 8,
  },

  // study/1 — no frame; the cross-type SRS review hub (§3).
  {
    screenId: "review",
    name: "Review",
    kind: "repo-only",
    variantOf: null,
    figmaNodeId: null,
    repoOnlyReason: "legacy-unreviewed",
    figmaCheckedAt: null,
    route: "/review",
    chrome: "app",
    impl: "placeholder",
    navGroup: "study",
    navOrder: 1,
  },
  // study/2 — no frame; sentence mining (§3).
  {
    screenId: "mining",
    name: "Mining",
    kind: "repo-only",
    variantOf: null,
    figmaNodeId: null,
    repoOnlyReason: "legacy-unreviewed",
    figmaCheckedAt: null,
    route: "/mining",
    chrome: "app",
    impl: "built",
    navGroup: "study",
    navOrder: 2,
  },
  // study/3 — built, no frame at this pass (R6) — named debt for Phase 2.
  {
    screenId: "playlists",
    name: "Playlists",
    kind: "repo-only",
    variantOf: null,
    figmaNodeId: null,
    repoOnlyReason: "legacy-unreviewed",
    figmaCheckedAt: null,
    route: "/playlists",
    chrome: "app",
    impl: "built",
    navGroup: "study",
    navOrder: 3,
  },
  // study/4 — no frame; a gamification surface (§3).
  {
    screenId: "challenges",
    name: "Challenges",
    kind: "repo-only",
    variantOf: null,
    figmaNodeId: null,
    repoOnlyReason: "legacy-unreviewed",
    figmaCheckedAt: null,
    route: "/challenges",
    chrome: "app",
    impl: "placeholder",
    navGroup: "study",
    navOrder: 4,
  },
  // study/5 — no frame; already adjudicated "hide in Phase 2" (§3), not
  // applied here per the binding constraint against the new IA.
  {
    screenId: "community",
    name: "Community",
    kind: "repo-only",
    variantOf: null,
    figmaNodeId: null,
    repoOnlyReason: "legacy-unreviewed",
    figmaCheckedAt: null,
    route: "/community",
    chrome: "app",
    impl: "built",
    navGroup: "study",
    navOrder: 5,
  },
  // study/6 — no frame; already adjudicated "hide in Phase 2" (§3).
  {
    screenId: "leaderboard",
    name: "Leaderboard",
    kind: "repo-only",
    variantOf: null,
    figmaNodeId: null,
    repoOnlyReason: "legacy-unreviewed",
    figmaCheckedAt: null,
    route: "/leaderboard",
    chrome: "app",
    impl: "built",
    navGroup: "study",
    navOrder: 6,
  },

  // insights/1 — designed, placeholder. §11.3 Companion Knowledge Assistant.
  {
    screenId: "sensei",
    name: "Companion Knowledge Assistant",
    kind: "screen",
    variantOf: null,
    figmaNodeId: "215:15164",
    repoOnlyReason: null,
    figmaCheckedAt: "2026-08-12",
    route: "/sensei",
    chrome: "app",
    impl: "placeholder",
    navGroup: "insights",
    navOrder: 1,
  },
  // insights/2 — designed, honest placeholder (Plan C1). Worked example.
  {
    screenId: "roadmap",
    name: "Roadmap",
    kind: "screen",
    variantOf: null,
    figmaNodeId: "64:2061",
    repoOnlyReason: null,
    figmaCheckedAt: "2026-08-12",
    route: "/roadmap",
    chrome: "app",
    impl: "placeholder",
    navGroup: "insights",
    navOrder: 2,
  },
  // insights/3 — no frame. §12.4 explicitly rules OUT `Growth Areas` as the
  // match for this route ("No. This is a persistent skill-progress map, not
  // a periodic report").
  {
    screenId: "weeklyReport",
    name: "Weekly Report",
    kind: "repo-only",
    variantOf: null,
    figmaNodeId: null,
    repoOnlyReason: "legacy-unreviewed",
    figmaCheckedAt: null,
    route: "/weekly-report",
    chrome: "app",
    impl: "placeholder",
    navGroup: "insights",
    navOrder: 3,
  },

  // progress/1 — designed, built; chrome contract already matches (§11.2).
  // Note: nav key is "journey" even though this is the Companion DIARY —
  // the §13.0 label collision (`journey` in Figma names the Roadmap) is a
  // known defect this phase records, not fixes (nav-baseline.fixture.ts
  // carries the same note).
  {
    screenId: "journey",
    name: "Companion Diary",
    kind: "screen",
    variantOf: null,
    figmaNodeId: "190:7376",
    repoOnlyReason: null,
    figmaCheckedAt: "2026-08-12",
    route: "/journal",
    chrome: "immersive",
    impl: "built",
    navGroup: "progress",
    navOrder: 1,
  },
  // progress/2 — no frame; a gamification surface (§3, §19.1's third
  // skill-taxonomy sighting notwithstanding — that lives on the Dashboard).
  {
    screenId: "statistics",
    name: "Statistics",
    kind: "repo-only",
    variantOf: null,
    figmaNodeId: null,
    repoOnlyReason: "legacy-unreviewed",
    figmaCheckedAt: null,
    route: "/statistics",
    chrome: "app",
    impl: "placeholder",
    navGroup: "progress",
    navOrder: 2,
  },
  // progress/3 — no frame; a gamification surface (§3).
  {
    screenId: "achievements",
    name: "Achievements",
    kind: "repo-only",
    variantOf: null,
    figmaNodeId: null,
    repoOnlyReason: "legacy-unreviewed",
    figmaCheckedAt: null,
    route: "/achievements",
    chrome: "app",
    impl: "placeholder",
    navGroup: "progress",
    navOrder: 3,
  },

  // account/1 — designed, built (far simpler than the frame — §18.2).
  {
    screenId: "profile",
    name: "Profile",
    kind: "screen",
    variantOf: null,
    figmaNodeId: "66:166",
    repoOnlyReason: null,
    figmaCheckedAt: "2026-08-12",
    route: "/profile",
    chrome: "app",
    impl: "built",
    navGroup: "account",
    navOrder: 1,
  },
  // account/2 — designed, placeholder. Frame's current name is "Global
  // settings" (rename pass verified 2026-08-12; figma-frame-map.md records
  // the trimmed string).
  {
    screenId: "settings",
    name: "Global settings",
    kind: "screen",
    variantOf: null,
    figmaNodeId: "220:16032",
    repoOnlyReason: null,
    figmaCheckedAt: "2026-08-12",
    route: "/settings",
    chrome: "app",
    impl: "placeholder",
    navGroup: "account",
    navOrder: 2,
  },

  // ===================================================================
  // Non-nav routes with a matching frame (screen or state-variant), not a
  // nav destination itself — navGroup/navOrder null throughout.
  // ===================================================================

  // 232:2's exam-runner detail. §10.8: Route "/jlpt/[id]" ≈.
  {
    screenId: "jlpt-practice-phase-1",
    name: "JLPT practice (phase 1)",
    kind: "screen",
    variantOf: null,
    figmaNodeId: "237:1690",
    repoOnlyReason: null,
    figmaCheckedAt: "2026-08-12",
    route: "/jlpt/[id]",
    chrome: "app",
    impl: "built",
    navGroup: null,
    navOrder: null,
  },
  // §6.4 — drawn as a modal overlay in Figma, built as a page in the repo;
  // §6.5's cluster verdict classifies it a screen, not an excluded modal.
  {
    screenId: "kanji-inspect",
    name: "Kanji inspect",
    kind: "screen",
    variantOf: null,
    figmaNodeId: "28:2041",
    repoOnlyReason: null,
    figmaCheckedAt: "2026-08-12",
    route: "/kanji/[id]",
    chrome: "app",
    impl: "built",
    navGroup: null,
    navOrder: null,
  },
  // §6.3 — chrome contract diverges in the design (Figma wants focus/
  // immersive); this repo's actual route sits under (app) — recorded as
  // measured, not as the design intends.
  {
    screenId: "kanji-lesson-practice-flashcard",
    name: "Kanji lesson practice (flashcard)",
    kind: "screen",
    variantOf: null,
    figmaNodeId: "280:1314",
    repoOnlyReason: null,
    figmaCheckedAt: "2026-08-12",
    route: "/kanji/review",
    chrome: "app",
    impl: "built",
    navGroup: null,
    navOrder: null,
  },
  // §18.1.
  {
    screenId: "login",
    name: "Login",
    kind: "screen",
    variantOf: null,
    figmaNodeId: "65:2",
    repoOnlyReason: null,
    figmaCheckedAt: "2026-08-12",
    route: "/login",
    chrome: "auth",
    impl: "built",
    navGroup: null,
    navOrder: null,
  },
  // §9.1 — the Shadowing Learning Mode workspace (Shadowing mode is built).
  {
    screenId: "shadowing-practice",
    name: "Shadowing Practice",
    kind: "screen",
    variantOf: null,
    figmaNodeId: "105:3088",
    repoOnlyReason: null,
    figmaCheckedAt: "2026-08-12",
    route: "/shadowing/[id]",
    chrome: "focus",
    impl: "built",
    navGroup: null,
    navOrder: null,
  },
  // §9.3 — a state-variant (a Learning Mode of the workspace) that HAS a
  // real, distinct route: shipped named for its sub-mode (Dictation) rather
  // than its mode (Listening Practice), per §9.0.
  {
    screenId: "dictation-in-shadowing",
    name: "Dictation (in shadowing)",
    kind: "state-variant",
    variantOf: "shadowing-practice",
    figmaNodeId: "123:2835",
    repoOnlyReason: null,
    figmaCheckedAt: "2026-08-12",
    route: "/shadowing/[id]/dictation",
    chrome: "focus",
    impl: "built",
    navGroup: null,
    navOrder: null,
  },
  // §8.1 — designed in full, shipped as a pure UpcomingScreen placeholder.
  {
    screenId: "explore-lessons",
    name: "Explore Lessons",
    kind: "screen",
    variantOf: null,
    figmaNodeId: "200:7705",
    repoOnlyReason: null,
    figmaCheckedAt: "2026-08-12",
    route: "/shadowing/explore",
    chrome: "app",
    impl: "placeholder",
    navGroup: null,
    navOrder: null,
  },

  // ===================================================================
  // Repo routes with no matching frame, and not a nav destination
  // (repo-only, legacy-unreviewed unless chrome is admin).
  // ===================================================================

  // §19.0 — "there is NO marketing landing frame anywhere in the 57... the
  // public front door of Korume is undesigned."
  {
    screenId: "landing-page",
    name: "Landing Page",
    kind: "repo-only",
    variantOf: null,
    figmaNodeId: null,
    repoOnlyReason: "legacy-unreviewed",
    figmaCheckedAt: null,
    route: "/",
    chrome: "marketing",
    impl: "built",
    navGroup: null,
    navOrder: null,
  },
  {
    screenId: "admin",
    name: "Admin",
    kind: "repo-only",
    variantOf: null,
    figmaNodeId: null,
    repoOnlyReason: "out-of-design-scope",
    figmaCheckedAt: null,
    route: "/admin",
    chrome: "admin",
    impl: "built",
    navGroup: null,
    navOrder: null,
  },
  {
    screenId: "admin-content",
    name: "Admin — Content",
    kind: "repo-only",
    variantOf: null,
    figmaNodeId: null,
    repoOnlyReason: "out-of-design-scope",
    figmaCheckedAt: null,
    route: "/admin/content",
    chrome: "admin",
    impl: "built",
    navGroup: null,
    navOrder: null,
  },
  {
    screenId: "admin-content-type",
    name: "Admin — Content Type",
    kind: "repo-only",
    variantOf: null,
    figmaNodeId: null,
    repoOnlyReason: "out-of-design-scope",
    figmaCheckedAt: null,
    route: "/admin/content/[type]",
    chrome: "admin",
    impl: "built",
    navGroup: null,
    navOrder: null,
  },
  // Tooling Figma will never cover — the ONLY legal use of out-of-design-scope
  // (R13/T10). Worked example.
  {
    screenId: "admin-style-guide",
    name: "Admin — Style Guide",
    kind: "repo-only",
    variantOf: null,
    figmaNodeId: null,
    repoOnlyReason: "out-of-design-scope",
    figmaCheckedAt: null,
    route: "/admin/style-guide",
    chrome: "admin",
    impl: "built",
    navGroup: null,
    navOrder: null,
  },
  {
    screenId: "admin-videos",
    name: "Admin — Videos",
    kind: "repo-only",
    variantOf: null,
    figmaNodeId: null,
    repoOnlyReason: "out-of-design-scope",
    figmaCheckedAt: null,
    route: "/admin/videos",
    chrome: "admin",
    impl: "built",
    navGroup: null,
    navOrder: null,
  },
  {
    screenId: "community-detail",
    name: "Community — Detail",
    kind: "repo-only",
    variantOf: null,
    figmaNodeId: null,
    repoOnlyReason: "legacy-unreviewed",
    figmaCheckedAt: null,
    route: "/community/[id]",
    chrome: "app",
    impl: "built",
    navGroup: null,
    navOrder: null,
  },
  {
    screenId: "community-peer-review",
    name: "Community — Peer Review",
    kind: "repo-only",
    variantOf: null,
    figmaNodeId: null,
    repoOnlyReason: "legacy-unreviewed",
    figmaCheckedAt: null,
    route: "/community/peer-review",
    chrome: "app",
    impl: "built",
    navGroup: null,
    navOrder: null,
  },
  // JUDGEMENT CALL (resolution given by the task, not re-litigated here):
  // an 8-line dead redirect() to /jlpt, superseded in Layer 5. Looks like
  // `kind: "deprecated"`, but T3 requires a non-null figmaNodeId for
  // "deprecated" and this route has no frame. Recorded repo-only +
  // legacy-unreviewed with the deprecation noted in `name`; the
  // deprecated-without-a-frame gap is a Phase 2 spec question, not amended
  // here.
  {
    screenId: "jlpt-test",
    name: "JLPT Test (deprecated — dead redirect to /jlpt, Layer 5)",
    kind: "repo-only",
    variantOf: null,
    figmaNodeId: null,
    repoOnlyReason: "legacy-unreviewed",
    figmaCheckedAt: null,
    route: "/jlpt-test",
    chrome: "app",
    impl: "built",
    navGroup: null,
    navOrder: null,
  },
  {
    screenId: "mining-review",
    name: "Mining — Review",
    kind: "repo-only",
    variantOf: null,
    figmaNodeId: null,
    repoOnlyReason: "legacy-unreviewed",
    figmaCheckedAt: null,
    route: "/mining/review",
    chrome: "app",
    impl: "built",
    navGroup: null,
    navOrder: null,
  },
  {
    screenId: "playlists-detail",
    name: "Playlists — Detail",
    kind: "repo-only",
    variantOf: null,
    figmaNodeId: null,
    repoOnlyReason: "legacy-unreviewed",
    figmaCheckedAt: null,
    route: "/playlists/[id]",
    chrome: "app",
    impl: "built",
    navGroup: null,
    navOrder: null,
  },
  {
    screenId: "reading-detail",
    name: "Reading — Detail",
    kind: "repo-only",
    variantOf: null,
    figmaNodeId: null,
    repoOnlyReason: "legacy-unreviewed",
    figmaCheckedAt: null,
    route: "/reading/[id]",
    chrome: "app",
    impl: "built",
    navGroup: null,
    navOrder: null,
  },
  {
    screenId: "register",
    name: "Register",
    kind: "repo-only",
    variantOf: null,
    figmaNodeId: null,
    repoOnlyReason: "legacy-unreviewed",
    figmaCheckedAt: null,
    route: "/register",
    chrome: "auth",
    impl: "built",
    navGroup: null,
    navOrder: null,
  },
  {
    screenId: "vocab-detail",
    name: "Vocabulary — Detail",
    kind: "repo-only",
    variantOf: null,
    figmaNodeId: null,
    repoOnlyReason: "legacy-unreviewed",
    figmaCheckedAt: null,
    route: "/vocab/[id]",
    chrome: "app",
    impl: "built",
    navGroup: null,
    navOrder: null,
  },
  {
    screenId: "vocab-review",
    name: "Vocabulary — Review",
    kind: "repo-only",
    variantOf: null,
    figmaNodeId: null,
    repoOnlyReason: "legacy-unreviewed",
    figmaCheckedAt: null,
    route: "/vocab/review",
    chrome: "app",
    impl: "built",
    navGroup: null,
    navOrder: null,
  },

  // ===================================================================
  // Designed, no route yet (R5) — legal and meaningful, NOT an error.
  // ===================================================================

  {
    screenId: "kanji-explorer",
    name: "Kanji explorer",
    kind: "screen",
    variantOf: null,
    figmaNodeId: "29:2890",
    repoOnlyReason: null,
    figmaCheckedAt: "2026-08-12",
    route: null,
    chrome: null,
    impl: "none",
    navGroup: null,
    navOrder: null,
  },
  {
    screenId: "kanji-library",
    name: "Kanji library",
    kind: "screen",
    variantOf: null,
    figmaNodeId: "280:3",
    repoOnlyReason: null,
    figmaCheckedAt: "2026-08-12",
    route: null,
    chrome: null,
    impl: "none",
    navGroup: null,
    navOrder: null,
  },
  // §7.2 — the ⌘K command palette. Heading tags it `CONFIRMED` (the screen
  // of record); the cluster verdict table (§7.3) agrees. Recorded as a
  // screen even though the surrounding prose muses it is "a panel, not a
  // canonical screen" — the two structured tags outweigh the aside.
  {
    screenId: "search-lesson",
    name: "Search lesson",
    kind: "screen",
    variantOf: null,
    figmaNodeId: "212:14610",
    repoOnlyReason: null,
    figmaCheckedAt: "2026-08-12",
    route: null,
    chrome: null,
    impl: "none",
    navGroup: null,
    navOrder: null,
  },
  {
    screenId: "summary-in-shadowing",
    name: "Summary (in shadowing)",
    kind: "screen",
    variantOf: null,
    figmaNodeId: "125:1030",
    repoOnlyReason: null,
    figmaCheckedAt: "2026-08-12",
    route: null,
    chrome: null,
    impl: "none",
    navGroup: null,
    navOrder: null,
  },
  {
    screenId: "jlpt-phase-test",
    name: "JLPT Phase test",
    kind: "screen",
    variantOf: null,
    figmaNodeId: "234:618",
    repoOnlyReason: null,
    figmaCheckedAt: "2026-08-12",
    route: null,
    chrome: null,
    impl: "none",
    navGroup: null,
    navOrder: null,
  },
  {
    screenId: "practice-result",
    name: "Practice result",
    kind: "screen",
    variantOf: null,
    figmaNodeId: "242:14234",
    repoOnlyReason: null,
    figmaCheckedAt: "2026-08-12",
    route: null,
    chrome: null,
    impl: "none",
    navGroup: null,
    navOrder: null,
  },
  {
    screenId: "review-mistake-after-jlpt-practice",
    name: "Review mistake (after JLPT practice)",
    kind: "screen",
    variantOf: null,
    figmaNodeId: "243:14899",
    repoOnlyReason: null,
    figmaCheckedAt: "2026-08-12",
    route: null,
    chrome: null,
    impl: "none",
    navGroup: null,
    navOrder: null,
  },
  {
    screenId: "companion-home",
    name: "Companion home",
    kind: "screen",
    variantOf: null,
    figmaNodeId: "156:1310",
    repoOnlyReason: null,
    figmaCheckedAt: "2026-08-12",
    route: null,
    chrome: null,
    impl: "none",
    navGroup: null,
    navOrder: null,
  },
  {
    screenId: "learning-memory",
    name: "Learning memory",
    kind: "screen",
    variantOf: null,
    figmaNodeId: "180:1770",
    repoOnlyReason: null,
    figmaCheckedAt: "2026-08-12",
    route: null,
    chrome: null,
    impl: "none",
    navGroup: null,
    navOrder: null,
  },
  {
    screenId: "growth-areas",
    name: "Growth Areas",
    kind: "screen",
    variantOf: null,
    figmaNodeId: "187:6556",
    repoOnlyReason: null,
    figmaCheckedAt: "2026-08-12",
    route: null,
    chrome: null,
    impl: "none",
    navGroup: null,
    navOrder: null,
  },
  {
    screenId: "roadmap-detail",
    name: "Roadmap detail",
    kind: "screen",
    variantOf: null,
    figmaNodeId: "180:2",
    repoOnlyReason: null,
    figmaCheckedAt: "2026-08-12",
    route: null,
    chrome: null,
    impl: "none",
    navGroup: null,
    navOrder: null,
  },
  {
    screenId: "conversation-memory",
    name: "Conversation memory",
    kind: "screen",
    variantOf: null,
    figmaNodeId: "184:3974",
    repoOnlyReason: null,
    figmaCheckedAt: "2026-08-12",
    route: null,
    chrome: null,
    impl: "none",
    navGroup: null,
    navOrder: null,
  },
  {
    screenId: "welcome-companion-page",
    name: "Welcome Companion page",
    kind: "screen",
    variantOf: null,
    figmaNodeId: "220:16766",
    repoOnlyReason: null,
    figmaCheckedAt: "2026-08-12",
    route: null,
    chrome: null,
    impl: "none",
    navGroup: null,
    navOrder: null,
  },
  {
    screenId: "generate-sensei",
    name: "Generate sensei",
    kind: "screen",
    variantOf: null,
    figmaNodeId: "111:1877",
    repoOnlyReason: null,
    figmaCheckedAt: "2026-08-12",
    route: null,
    chrome: null,
    impl: "none",
    navGroup: null,
    navOrder: null,
  },
  // The live-session frame — see the "speaking" entry above for why this
  // has no route of its own (§15.6: "none (session UI exists in-page)").
  {
    screenId: "conversation-practice",
    name: "Conversation practice",
    kind: "screen",
    variantOf: null,
    figmaNodeId: "44:7289",
    repoOnlyReason: null,
    figmaCheckedAt: "2026-08-12",
    route: null,
    chrome: null,
    impl: "none",
    navGroup: null,
    navOrder: null,
  },
  {
    screenId: "pronunciation-library",
    name: "Pronunciation library",
    kind: "screen",
    variantOf: null,
    figmaNodeId: "37:4955",
    repoOnlyReason: null,
    figmaCheckedAt: "2026-08-12",
    route: null,
    chrome: null,
    impl: "none",
    navGroup: null,
    navOrder: null,
  },
  {
    screenId: "pronunciation-detail",
    name: "Pronunciation detail",
    kind: "screen",
    variantOf: null,
    figmaNodeId: "36:4117",
    repoOnlyReason: null,
    figmaCheckedAt: "2026-08-12",
    route: null,
    chrome: null,
    impl: "none",
    navGroup: null,
    navOrder: null,
  },
  // JUDGEMENT CALL: the frame's layer name is "Grammar analysis" (kept
  // verbatim in `name`, per the Dashboard precedent) even though §17.1
  // finds its real identity is a sentence parser ("Sentence Analysis"),
  // distinct from the /grammar catalogue. See the "grammar" repo-only entry
  // above.
  {
    screenId: "grammar-analysis",
    name: "Grammar analysis",
    kind: "screen",
    variantOf: null,
    figmaNodeId: "284:1464",
    repoOnlyReason: null,
    figmaCheckedAt: "2026-08-12",
    route: null,
    chrome: null,
    impl: "none",
    navGroup: null,
    navOrder: null,
  },
  {
    screenId: "edit-profile",
    name: "Edit profile",
    kind: "screen",
    variantOf: null,
    figmaNodeId: "67:595",
    repoOnlyReason: null,
    figmaCheckedAt: "2026-08-12",
    route: null,
    chrome: null,
    impl: "none",
    navGroup: null,
    navOrder: null,
  },
  // Worked example.
  {
    screenId: "pricing",
    name: "Pricing",
    kind: "screen",
    variantOf: null,
    figmaNodeId: "74:564",
    repoOnlyReason: null,
    figmaCheckedAt: "2026-08-12",
    route: null,
    chrome: null,
    impl: "none",
    navGroup: null,
    navOrder: null,
  },
  {
    screenId: "checkout",
    name: "Checkout",
    kind: "screen",
    variantOf: null,
    figmaNodeId: "209:14032",
    repoOnlyReason: null,
    figmaCheckedAt: "2026-08-12",
    route: null,
    chrome: null,
    impl: "none",
    navGroup: null,
    navOrder: null,
  },
  {
    screenId: "faq",
    name: "FAQ",
    kind: "screen",
    variantOf: null,
    figmaNodeId: "75:1424",
    repoOnlyReason: null,
    figmaCheckedAt: "2026-08-12",
    route: null,
    chrome: null,
    impl: "none",
    navGroup: null,
    navOrder: null,
  },
  {
    screenId: "quickstart",
    name: "QuickStart",
    kind: "screen",
    variantOf: null,
    figmaNodeId: "111:1556",
    repoOnlyReason: null,
    figmaCheckedAt: "2026-08-12",
    route: null,
    chrome: null,
    impl: "none",
    navGroup: null,
    navOrder: null,
  },

  // ===================================================================
  // State-variants with no route (R11) — never promoted to screens.
  // ===================================================================

  // Worked example.
  {
    screenId: "explore-lessons-with-preview",
    name: "Explore Lessons (with preview)",
    kind: "state-variant",
    variantOf: "explore-lessons",
    figmaNodeId: "200:10726",
    repoOnlyReason: null,
    figmaCheckedAt: "2026-08-12",
    route: null,
    chrome: null,
    impl: "none",
    navGroup: null,
    navOrder: null,
  },
  {
    screenId: "search-lesson-searched",
    name: "Search lesson (searched)",
    kind: "state-variant",
    variantOf: "search-lesson",
    figmaNodeId: "212:14753",
    repoOnlyReason: null,
    figmaCheckedAt: "2026-08-12",
    route: null,
    chrome: null,
    impl: "none",
    navGroup: null,
    navOrder: null,
  },
  {
    screenId: "pronunciation-in-shadowing",
    name: "Pronunciation (in shadowing)",
    kind: "state-variant",
    variantOf: "shadowing-practice",
    figmaNodeId: "120:2027",
    repoOnlyReason: null,
    figmaCheckedAt: "2026-08-12",
    route: null,
    chrome: null,
    impl: "none",
    navGroup: null,
    navOrder: null,
  },
  {
    screenId: "finish-phase-1",
    name: "Finish phase 1",
    kind: "state-variant",
    variantOf: "jlpt-practice-phase-1",
    figmaNodeId: "237:6708",
    repoOnlyReason: null,
    figmaCheckedAt: "2026-08-12",
    route: null,
    chrome: null,
    impl: "none",
    navGroup: null,
    navOrder: null,
  },
  {
    screenId: "to-phase-2-ready",
    name: "To phase 2 (ready)",
    kind: "state-variant",
    variantOf: "jlpt-practice-phase-1",
    figmaNodeId: "234:1639",
    repoOnlyReason: null,
    figmaCheckedAt: "2026-08-12",
    route: null,
    chrome: null,
    impl: "none",
    navGroup: null,
    navOrder: null,
  },
  {
    screenId: "to-phase-2-countdown",
    name: "To phase 2 (countdown)",
    kind: "state-variant",
    variantOf: "jlpt-practice-phase-1",
    figmaNodeId: "234:1667",
    repoOnlyReason: null,
    figmaCheckedAt: "2026-08-12",
    route: null,
    chrome: null,
    impl: "none",
    navGroup: null,
    navOrder: null,
  },
  {
    screenId: "jlpt-practice-phase-2",
    name: "JLPT practice (phase 2)",
    kind: "state-variant",
    variantOf: "jlpt-practice-phase-1",
    figmaNodeId: "240:12992",
    repoOnlyReason: null,
    figmaCheckedAt: "2026-08-12",
    route: null,
    chrome: null,
    impl: "none",
    navGroup: null,
    navOrder: null,
  },
  {
    screenId: "review-mistake-more-detail",
    name: "Review mistake (more detail)",
    kind: "state-variant",
    variantOf: "review-mistake-after-jlpt-practice",
    figmaNodeId: "243:15364",
    repoOnlyReason: null,
    figmaCheckedAt: "2026-08-12",
    route: null,
    chrome: null,
    impl: "none",
    navGroup: null,
    navOrder: null,
  },
  // §11.4 — misnamed frame: it is the Companion DIARY's empty state, not
  // Companion home's. variantOf points at "journey" (the registered
  // screenId for 190:7376 Companion Diary), not a "companion-diary" id.
  {
    screenId: "empty-state-companion-home",
    name: "Empty state (Companion home)",
    kind: "state-variant",
    variantOf: "journey",
    figmaNodeId: "216:15648",
    repoOnlyReason: null,
    figmaCheckedAt: "2026-08-12",
    route: null,
    chrome: null,
    impl: "none",
    navGroup: null,
    navOrder: null,
  },
  {
    screenId: "generate-done",
    name: "Generate done",
    kind: "state-variant",
    variantOf: "generate-sensei",
    figmaNodeId: "111:1963",
    repoOnlyReason: null,
    figmaCheckedAt: "2026-08-12",
    route: null,
    chrome: null,
    impl: "none",
    navGroup: null,
    navOrder: null,
  },
  // variantOf "speaking" — the registered screenId for 170:9364
  // (Conversation practice library), the screen this preview overlays.
  {
    screenId: "quick-preview-panel-conversation-practice",
    name: "Quick preview panel: Conversation practice",
    kind: "state-variant",
    variantOf: "speaking",
    figmaNodeId: "180:1129",
    repoOnlyReason: null,
    figmaCheckedAt: "2026-08-12",
    route: null,
    chrome: null,
    impl: "none",
    navGroup: null,
    navOrder: null,
  },
];
